import { World, Region, TimePeriod } from '../types';

// Detailed region descriptions for each time period
const REGION_DETAILS: { [key: string]: { [key: string]: string } } = {
    "prehistoric-era": {
        "African Origins": "🏺 The birthplace of humanity, where our earliest ancestors evolved from apes into humans. Archaeological sites like Olduvai Gorge reveal tool-making Homo habilis, while Lucy and other Australopithecus fossils tell the story of bipedalism. Cave paintings at Blombos Cave show early artistic expression, and the development of complex language began here. The Great Rift Valley served as humanity's nursery, where fire was first controlled and stone tools perfected.",
        "Paleolithic Europe": "🦣 A harsh Ice Age landscape where Cro-Magnon humans created the world's first masterpieces in caves like Lascaux and Altamira. These hunter-gatherers developed sophisticated tools, jewelry, and burial rituals. They hunted mammoth and reindeer across frozen steppes, created Venus figurines celebrating fertility, and established trade networks spanning thousands of miles. Their art reveals complex spiritual beliefs and deep understanding of animal behavior.",
        "Neolithic Settlements": "🌾 The revolutionary transition from hunting to farming that changed everything. Sites like Çatalhöyük in Turkey show early urban planning, while Göbekli Tepe reveals complex religious structures predating agriculture. Farmers domesticated wheat, barley, cattle, and sheep, creating surplus food that enabled specialization. Pottery, weaving, and monumental architecture emerged as communities grew into the first towns.",
        "Early Americas": "🗿 Bold adventurers who crossed the Bering land bridge to populate two virgin continents. Paleo-Indians hunted massive megafauna like mammoths and giant ground sloths using sophisticated Clovis points. They adapted to diverse environments from Arctic tundra to Amazonian rainforests, developing unique cultures like the Ancestral Puebloans who built cliff dwellings, and creating the first art in the Americas.",
        "Australian Aboriginals": "🎨 The world's oldest continuous culture, arriving by boat 65,000 years ago and developing the most sophisticated understanding of their environment ever achieved. Their Dreamtime stories encode geological and astronomical knowledge passed down through millennia. They created the world's first ground paintings, developed complex fire-stick farming, and maintained trade networks across the entire continent."
    },
    "ancient-civilizations": {
        "Mesopotamian Cradle": "🏛️ The world's first civilization arose between the Tigris and Euphrates rivers, creating humanity's first cities, laws, and writing system. Sumerians built towering ziggurats to honor their gods, invented the wheel and the plow, and created cuneiform writing. The Epic of Gilgamesh, humanity's first great literature, emerged here. Kings like Hammurabi created the first written law codes, while Babylon became synonymous with urban grandeur and the legendary Hanging Gardens.",
        "Pharaonic Egypt": "🔺 A civilization that lasted 3,000 years along the life-giving Nile River, creating monuments that still astound us today. The pyramids of Giza represent the pinnacle of ancient engineering, while the Sphinx guards eternal mysteries. Pharaohs like Khufu, Hatshepsut, and Ramesses II ruled as living gods, mummified for eternal life. Hieroglyphic writing preserved their stories, medicine advanced through mummification, and their art achieved timeless beauty.",
        "Indus Valley Cities": "🏺 A remarkably advanced Bronze Age civilization with sophisticated urban planning that modern cities still admire. Harappa and Mohenjo-daro featured covered sewers, standardized weights and measures, and peaceful societies with no evidence of warfare. Their undeciphered script tantalizes archaeologists, while their precise urban grids, advanced bathhouses, and international trade networks reveal a civilization ahead of its time.",
        "Shang Dynasty China": "🐉 China's first historically confirmed dynasty, ruling from fortified cities and perfecting bronze-working technology. They created the most sophisticated bronze vessels ever made, developed the earliest form of Chinese writing on oracle bones used for divination, and established patterns of Chinese kingship that lasted millennia. Their royal tombs contained elaborate bronze chariots and sacrificed servants, revealing a complex stratified society.",
        "Minoan Crete": "🌊 Europe's first advanced civilization, centered on the island of Crete with magnificent palaces like Knossos. The Minoans were master mariners who dominated Mediterranean trade, created vibrant frescoes of dolphins and bull-leapers, and worshipped a snake goddess. Their Linear A script remains undeciphered, adding mystery to their sudden disappearance, possibly due to the catastrophic eruption of Thera volcano.",
        "Olmec Mesoamerica": "🗿 Mesoamerica's 'mother culture' that laid foundations for all later civilizations in the region. Famous for their colossal stone heads weighing up to 50 tons, the Olmecs developed the first writing system in the Americas, created the concept of zero, and established the ritual ball game. Their sophisticated calendar and astronomical observations influenced Maya and Aztec civilizations centuries later."
    },
    "classical-antiquity": {
        "Athenian Democracy": "🏛️ The birthplace of democracy, philosophy, and theater that laid the intellectual foundations of Western civilization. In the agora, citizens debated politics while Socrates questioned everything, Plato described ideal republics, and Aristotle catalogued knowledge. The Parthenon crowned the Acropolis as a temple to Athena, while tragedians like Sophocles explored human nature. Athens' golden age under Pericles saw democracy flourish, though limited to male citizens.",
        "Roman Empire": "🦅 The greatest empire in ancient history, stretching from Britain to Mesopotamia, united by Roman law, engineering, and military might. Roman legions conquered with discipline and organization, while Roman engineers built roads, aqueducts, and the Colosseum that still inspire awe. Latin became the language of learning, Roman law forms the basis of modern legal systems, and Pax Romana brought two centuries of peace to the Mediterranean world.",
        "Persian Empires": "👑 A succession of vast empires that connected East and West, from Cyrus the Great's tolerant Achaemenid Empire to the Sassanid revival. Persepolis showcased imperial grandeur with its massive columns and relief sculptures celebrating the diversity of the empire. The Royal Road enabled communication across thousands of miles, while Persian gardens influenced Islamic art. Zoroastrianism, with its concepts of good versus evil and final judgment, influenced later religions.",
        "Mauryan India": "🕉️ India's first empire, uniting most of the subcontinent under rulers like Chandragupta Maurya and his grandson Ashoka. After converting to Buddhism following the bloody Kalinga War, Ashoka promoted non-violence and built thousands of stupas. His edicts, carved on rocks and pillars throughout the empire, promoted religious tolerance and moral governance. The capital at Pataliputra was one of the world's largest cities.",
        "Han Dynasty China": "🐲 China's longest-lasting dynasty that established patterns of Chinese governance lasting two millennia. The Han perfected the Silk Road trade network connecting China to Rome, invented paper, developed advanced metallurgy, and created the first seismograph. Confucianism became state ideology while the Mandate of Heaven justified imperial rule. Han armies expanded Chinese territory while scholars compiled histories and philosophies that shaped Chinese thought.",
        "Celtic Tribes": "🍀 Fierce warriors and skilled craftsmen who dominated Europe before Roman conquest, creating beautiful art in distinctive La Tène style. Celtic druids preserved oral traditions and astronomical knowledge, while Celtic warriors terrified Roman armies with their courage and distinctive war cries. Their hill forts crowned European landscapes, and their metalworking produced some of the finest Iron Age artifacts ever discovered."
    },
    "post-classical": {
        "Islamic Golden Age": "☪️ A period of unprecedented intellectual flowering that preserved and expanded upon classical knowledge while making revolutionary discoveries. In Baghdad's House of Wisdom, scholars translated Greek texts while making breakthroughs in mathematics (algebra), medicine (surgery), astronomy (astrolabe), and philosophy. Cities like Cordoba, Cairo, and Baghdad became centers of learning where Islamic, Christian, and Jewish scholars collaborated.",
        "Byzantine Empire": "⛪ The continuation of the Roman Empire in the East, centered on the magnificent city of Constantinople with its jewel, Hagia Sophia. Byzantine emperors like Justinian reconquered much of the former Western Empire while codifying Roman law in the Corpus Juris Civilis. Byzantine art achieved sublime beauty in mosaics and icons, while Greek fire protected the empire's walls. The empire served as guardian of classical learning and Orthodox Christianity.",
        "Tang Dynasty China": "🏮 China's cosmopolitan golden age when Chang'an became the world's largest city with over one million inhabitants. The Tang perfected the civil service examination system, welcomed foreign merchants along the Silk Road, and saw Buddhism flourish alongside Confucianism and Taoism. Poets like Li Bai and Du Fu created timeless verses, while Empress Wu Zetian became China's only female emperor.",
        "Feudal Japan": "⚔️ The emergence of samurai culture and distinctive Japanese aesthetics during the Heian period. Noble families like the Fujiwara dominated the imperial court while provincial warriors developed bushido, the way of the warrior. Lady Murasaki wrote The Tale of Genji, considered the world's first novel, while Japanese Buddhism adapted Chinese forms into uniquely Japanese expressions like Zen.",
        "Maya Civilization": "🗓️ Mesoamerica's most intellectually advanced civilization, creating sophisticated calendars, mathematical concepts including zero, and the most advanced writing system in the pre-Columbian Americas. Maya city-states like Tikal and Palenque featured towering pyramids and intricate stone carvings. Their astronomical observations were remarkably accurate, and their art achieved extraordinary beauty in jade, ceramics, and murals.",
        "Viking Territories": "⚡ Norse seafarers who raided, traded, and explored from Greenland to Constantinople, spreading Scandinavian culture across northern Europe. Vikings perfected longship technology enabling ocean voyages, established the first European settlement in North America at L'Anse aux Meadows, and created rich oral traditions preserved in sagas. Their raids transformed European politics while their trade networks connected Arctic furs to Byzantine silk.",
        "Ethiopian Empire": "👑 The ancient Christian kingdom of Aksum controlled Red Sea trade between Rome and India, creating its own coinage and erecting massive stone obelisks. Later Ethiopian emperors claimed descent from Solomon and Sheba while defending their mountain kingdom against Islamic expansion. The rock-hewn churches of Lalibela represent architectural marvels carved directly from living rock."
    },
    "high-middle-ages": {
        "Medieval Europe": "🏰 The age of chivalry, crusades, and cathedral building when feudalism structured society around knights, lords, and serfs. Gothic cathedrals like Notre-Dame and Chartres reached toward heaven with flying buttresses and stained glass windows. Universities at Bologna, Paris, and Oxford pioneered scholastic learning, while troubadours sang of courtly love. The Crusades brought Europeans into contact with Islamic and Byzantine civilizations.",
        "Mongol Empire": "🏹 The largest contiguous land empire in history, stretching from Korea to Hungary under leaders like Genghis Khan and his successors. Mongol horsemen conquered with superior mobility and psychological warfare, but then facilitated trade and cultural exchange along the Silk Road. The Pax Mongolica enabled unprecedented communication between East and West, while Mongol tolerance allowed conquered peoples to maintain their cultures.",
        "Crusader States": "✝️ European Christian kingdoms established in the Holy Land during the Crusades, representing the intersection of Western and Eastern cultures. The Templars and Hospitallers created the first international military orders, while Crusader castles like Krak des Chevaliers showcased advanced military architecture. These states facilitated cultural exchange, introducing Europeans to Eastern spices, mathematics, and philosophy.",
        "Islamic Spain": "🕌 Al-Andalus represented the pinnacle of Islamic civilization in Europe, where Cordoba rivaled Baghdad as a center of learning. The Great Mosque of Cordoba, with its forest of horseshoe arches, exemplified Moorish architecture. Scholars in Cordoba translated Aristotle and preserved classical knowledge, while poets and philosophers like Averroes contributed to world literature and thought. Christians, Muslims, and Jews coexisted in relative harmony.",
        "Song Dynasty China": "🎨 China's renaissance period that saw remarkable technological innovation and artistic achievement. Song China invented gunpowder, the compass, and movable type printing centuries before Europe. Neo-Confucianism reached philosophical maturity, while landscape painting achieved sublime beauty. Despite military pressures from northern neighbors, Song China was the world's most prosperous and technologically advanced civilization.",
        "Khmer Empire": "🏛️ Southeast Asia's greatest empire, centered on the magnificent temple complex of Angkor Wat, the world's largest religious monument. Khmer kings like Jayavarman VII controlled trade routes between China and India while perfecting sophisticated hydraulic engineering systems. Their temples synthesized Hindu and Buddhist architecture, while Khmer sculpture achieved extraordinary grace and beauty.",
        "Mali Empire": "💰 West Africa's golden empire that controlled trans-Saharan gold and salt trade, making Timbuktu synonymous with fabulous wealth and learning. Mansa Musa's legendary pilgrimage to Mecca distributed so much gold in Cairo that it affected Mediterranean gold prices for decades. Timbuktu's Sankore University attracted scholars from across the Islamic world, while griots preserved historical traditions in epic poetry.",
        "Aztec Empire": "🐍 Mesoamerica's most powerful empire, centered on the magnificent island capital of Tenochtitlan in Lake Texcoco. Aztec chinampas (floating gardens) fed a population larger than contemporary European cities, while the Great Temple dominated the urban landscape. Aztec warriors captured enemies for elaborate religious ceremonies, while their calendar stone encoded sophisticated astronomical knowledge."
    },
    "late-middle-ages": {
        "Renaissance Italy": "🎨 The birthplace of the Renaissance where humanism, artistic innovation, and scientific inquiry flourished in wealthy city-states. Florence under the Medici became Europe's banking capital while nurturing geniuses like Leonardo da Vinci, Michelangelo, and Brunelleschi. The Sistine Chapel ceiling and David sculpture represent artistic pinnacles, while Machiavelli's 'The Prince' revolutionized political thought.",
        "Ottoman Empire": "🌙 The last great Islamic empire that conquered Constantinople and controlled Eastern Mediterranean trade for centuries. Ottoman sultans like Suleiman the Magnificent expanded the empire to the gates of Vienna while patronizing magnificent architecture like the Blue Mosque. The Ottoman system integrated diverse peoples through the millet system, while Janissaries provided elite military force.",
        "Ming Dynasty China": "🏮 China's native dynasty that restored Chinese rule after overthrowing the Mongols, building the Forbidden City and perfecting the Great Wall. Admiral Zheng He's treasure fleets explored the Indian Ocean decades before Columbus, while Ming porcelain and silk were prized worldwide. The Ming restored Confucian orthodoxy and created one of history's most sophisticated bureaucracies.",
        "Inca Empire": "☀️ South America's greatest empire, stretching along the Andes from Ecuador to Chile, connected by an amazing road system and ruled from Cusco, the 'navel of the world.' Inca engineers perfected sophisticated stone masonry without mortar, while their administrative system managed millions of subjects without written language. Machu Picchu represents the pinnacle of Inca architecture and urban planning.",
        "Reconquista Spain": "👑 The centuries-long Christian reconquest of Islamic Spain culminating in 1492 with Granada's fall and Columbus's voyage. Spanish knights developed a crusading mentality that would later drive New World conquests, while the Catholic Monarchs Ferdinand and Isabella united Spain and sponsored global exploration. The Alhambra's beauty contrasted with the Inquisition's severity.",
        "Hanseatic League": "⚓ Northern Europe's powerful merchant confederation that dominated Baltic and North Sea trade from London to Novgorod. Hanseatic merchants established trading posts called kontors, while cities like Lübeck and Hamburg grew wealthy from commerce. The League's demokratic assemblies and standardized laws facilitated international trade while spreading German culture eastward.",
        "Timurid Empire": "💎 Central Asia's cultured empire under Tamerlane and his successors, centered on the magnificent city of Samarkand with its azure-tiled mosques and madrasas. Despite Tamerlane's brutal conquests, Timurid rulers patronized art, architecture, and learning. The Timurid prince Babur would later found the Mughal Empire in India, while Timurid artistic styles influenced Islamic art for centuries."
    },
    "early-modern": {
        "Colonial Americas": "⛵ European colonies that transformed two continents through colonization, creating new hybrid societies blending European, African, and indigenous cultures. Spanish conquistadors like Cortés and Pizarro toppled the Aztec and Inca empires, while English colonists established tobacco plantations and Puritan communities. The Atlantic slave trade brought millions of Africans to work sugar and tobacco plantations, creating creole cultures throughout the Americas.",
        "Mughal India": "🕌 India's Islamic empire that created a synthesis of Persian, Islamic, and Hindu cultures under rulers like Akbar the Great. The Taj Mahal represents the pinnacle of Mughal architecture, while Mughal miniature painting achieved extraordinary refinement. Akbar's policy of religious tolerance created a golden age, though later rulers like Aurangzeb imposed orthodox Islam, contributing to the empire's decline.",
        "Qing China": "🐲 China's last imperial dynasty, established by Manchu conquerors who adopted Chinese culture while maintaining their distinct identity. Qing China reached its greatest territorial extent under Emperor Qianlong, while maintaining strict control over foreign trade through the Canton system. Chinese porcelain, tea, and silk were prized worldwide, though the empire's isolationist policies would later prove problematic.",
        "Tokugawa Japan": "🏯 Japan's most peaceful era under the Tokugawa shogunate's rigid social hierarchy and isolation policy (sakoku). Edo (Tokyo) became the world's largest city while Japanese culture flowered in ukiyo-e woodblock prints, kabuki theater, and haiku poetry. The samurai class maintained their privileges while merchants grew wealthy, creating tensions that would eventually topple the system.",
        "Ottoman Empire": "🌙 The 'Sick Man of Europe' began its long decline while still controlling vast territories from the Balkans to Arabia. Ottoman sultans struggled with European military advances while provincial governors gained autonomy. However, Ottoman architecture continued to flourish, and the empire remained a major power requiring European diplomatic attention.",
        "Russian Empire": "❄️ Russia's expansion under Peter the Great and Catherine the Great transformed a backward principality into Europe's largest empire. St. Petersburg became Russia's 'window to Europe' with magnificent palaces and Western customs, while Russian armies conquered territory stretching to Alaska. Serfdom bound peasants to the land while nobles enjoyed European culture and Enlightenment ideas.",
        "Enlightenment Europe": "💡 The Age of Reason when philosophers like Voltaire, Rousseau, and Diderot championed rational thought, religious tolerance, and individual rights. Scientific revolution figures like Newton and Galileo unlocked natural laws, while Enlightenment salons and coffeehouses spread new ideas. These concepts would inspire democratic revolutions and challenge traditional authority.",
        "African Kingdoms": "👑 Powerful African states like Kongo, Ethiopia, and the Swahili city-states that maintained independence while engaging in global trade. The Kingdom of Kongo initially welcomed Portuguese missionaries and traders, while Ethiopian emperors corresponded with European monarchs as equals. Swahili merchants facilitated Indian Ocean trade, while kingdoms like Buganda and Ashanti controlled regional commerce."
    },
    "industrial-age": {
        "Industrial Britain": "🏭 The world's first industrial nation where steam engines, textile mills, and railway networks revolutionized production and transportation. Cities like Manchester and Birmingham became 'workshops of the world' while British manufactured goods flooded global markets. The British Empire expanded to control a quarter of the world's population, while social reformers like Dickens exposed industrial society's dark side.",
        "Expanding America": "🚂 A young nation that expanded from 13 colonies to a continental power through manifest destiny, territorial purchases, and conquest. The California Gold Rush, transcontinental railroad, and Civil War defined American character while millions of immigrants sought opportunity in the 'land of the free.' American innovations like the telegraph and light bulb would change the world.",
        "Meiji Japan": "🏯 Japan's remarkable transformation from feudal isolation to modern industrial power in just decades. The Meiji Restoration abolished the samurai class while adopting Western technology, education, and government systems. Japanese leaders sent missions worldwide to study best practices, while 'rich country, strong army' became the national slogan driving rapid modernization.",
        "Imperial Germany": "🦅 Europe's newest and most dynamic power under Bismarck's leadership, unifying German states through 'blood and iron' while becoming Europe's industrial powerhouse. German universities led scientific research, while German engineering and chemistry set world standards. However, Germany's rapid rise and aggressive diplomacy would contribute to global tensions and eventual world war.",
        "Tsarist Russia": "❄️ Europe's most autocratic empire struggling to modernize while maintaining traditional authority. The emancipation of serfs in 1861 began social transformation, while the Trans-Siberian Railway connected the vast empire. Russian literature through Tolstoy and Dostoevsky explored the human condition, while revolutionary movements challenged tsarist rule.",
        "Colonial Africa": "🌍 The continent carved up by European powers during the 'Scramble for Africa,' with ancient kingdoms and traditional societies disrupted by colonial rule. The discovery of diamonds and gold in South Africa attracted European settlement, while the construction of railways and telegraph lines integrated Africa into the global economy. African resistance movements like the Zulu Wars challenged colonial expansion.",
        "Qing China": "🐲 The 'Middle Kingdom' struggled with Western imperialism and internal rebellions like the Taiping Rebellion that killed millions. Opium Wars opened Chinese ports to foreign trade while humiliating the Qing court. Reform movements attempted modernization, but the empire remained weakened by foreign concessions and internal decay.",
        "Latin American Republics": "🗽 New nations that gained independence from Spain and Portugal while struggling to establish stable governments and modern economies. Leaders like Simón Bolívar dreamed of continental unity, while countries like Argentina and Brazil attracted European immigrants. However, political instability and economic dependence on raw material exports limited development."
    },
    "modern-world": {
        "Soviet Union": "☭ The world's first communist state that industrialized rapidly under Stalin while creating a totalitarian system that controlled every aspect of life. The Soviet victory over Nazi Germany came at enormous cost, while the Cold War divided the world into competing ideological blocs. Soviet achievements in space exploration and nuclear weapons made it a superpower, though economic stagnation eventually led to collapse.",
        "Nazi Germany": "卐 Hitler's totalitarian regime that plunged the world into its deadliest conflict while perpetrating the Holocaust, history's most systematic genocide. Nazi ideology combined radical nationalism with racial theory, while German military innovations like blitzkrieg temporarily dominated Europe. The regime's defeat in 1945 ended fascism as a major political force.",
        "Imperial Japan": "🌅 Japan's aggressive expansion throughout East Asia that brought it into conflict with China, Britain, and ultimately the United States. Japanese militarism dominated politics while the emperor cult justified expansion. Pearl Harbor brought America into World War II, while atomic bombs on Hiroshima and Nagasaki ended the war and Japan's imperial ambitions.",
        "United States": "🦅 America emerged from two world wars as the world's dominant superpower, leading the 'free world' against communist expansion. American economic and military power shaped the postwar order, while American culture spread globally through Hollywood and popular music. The civil rights movement struggled to extend democratic ideals to all Americans.",
        "British Empire": "🇬🇧 The largest empire in history began its transformation into the Commonwealth as colonies gained independence. Britain's 'special relationship' with America helped win two world wars, while the creation of the welfare state transformed British society. However, economic decline and decolonization reduced Britain from global hegemon to regional power.",
        "Third Reich": "⚡ The Nazi empire that briefly dominated Europe through military conquest and racial ideology, creating a 'new order' based on German supremacy and the elimination of 'undesirable' populations. The Holocaust machinery revealed the depths of human evil, while Nazi war crimes led to new concepts of international justice.",
        "Communist China": "🔴 Mao Zedong's revolutionary movement that ended China's 'century of humiliation' while creating a communist state that would reshape Chinese society. The Great Leap Forward and Cultural Revolution caused enormous suffering, while China's eventual economic reforms would transform it into a global power by century's end.",
        "Decolonizing Africa": "🌍 The rapid end of European colonial rule as African nations gained independence, often through struggle and sometimes violence. Leaders like Nkrumah, Kenyatta, and Mandela led liberation movements while creating new nations from colonial boundaries. The challenges of nation-building, economic development, and Cold War politics shaped the post-colonial experience.",
        "Middle East": "🕌 The region's strategic importance grew with oil discoveries while the creation of Israel and Arab nationalism created ongoing conflicts. The Suez Crisis, Six-Day War, and Iranian Revolution reshaped regional politics, while oil wealth transformed traditional societies. Islamic revival movements challenged Western influence while internal conflicts displaced millions."
    },
    "contemporary-era": {
        "Silicon Valley": "💻 The world's technology capital where innovations like personal computers, the internet, and smartphones revolutionized human communication and commerce. Companies like Apple, Google, and Facebook created new industries while their founders became global celebrities. The 'dot-com' boom and bust showed both the promise and perils of technological innovation.",
        "European Union": "🇪🇺 Europe's unprecedented experiment in supranational integration that created the world's largest single market while promoting peace and prosperity. The fall of the Berlin Wall enabled EU expansion eastward, while the euro created a common currency for most members. However, challenges like Brexit and refugee crises test European unity.",
        "Rising China": "🐲 China's economic miracle transformed it from isolated communist state to global manufacturing center and emerging superpower. Deng Xiaoping's reforms unleashed Chinese entrepreneurship while maintaining Communist Party control. China's Belt and Road Initiative seeks to recreate ancient Silk Road trade networks on a global scale.",
        "Post-Soviet Russia": "🇷🇺 Russia's difficult transition from communist superpower to capitalist state under leaders like Yeltsin and Putin. Economic collapse and political chaos marked the 1990s, while Putin's rule restored state authority and challenged Western dominance. Russia's vast natural resources and nuclear arsenal maintain its global influence.",
        "Middle East": "🕌 The region remains a global flashpoint with ongoing conflicts in Iraq, Syria, and Yemen while oil wealth continues to shape international relations. The Arab Spring raised hopes for democratic change, while the rise of ISIS revealed the dangers of state collapse. Iran's nuclear program and Israel's security concerns complicate regional dynamics.",
        "Emerging Africa": "🌍 Africa's young population and natural resources offer enormous potential while challenges like poverty, disease, and conflict persist. Countries like Nigeria, Kenya, and Rwanda show impressive economic growth, while innovations in mobile banking and renewable energy suggest promising futures. However, climate change and political instability threaten progress.",
        "Digital Asia": "📱 Asia's embrace of digital technology has created new economic powerhouses in South Korea, Singapore, and India. K-pop and anime spread Asian culture globally, while Asian tech companies compete with Western giants. However, tensions between China and its neighbors, plus North Korea's nuclear program, create regional instability.",
        "Latin America": "🏛️ The region struggles with inequality, drug violence, and political polarization while countries like Brazil and Mexico remain major emerging economies. Climate change threatens the Amazon rainforest, while migration patterns reshape both regional and global demographics. Democratic institutions face challenges from populist movements.",
        "Arctic Nations": "🧊 Climate change is rapidly transforming the Arctic, opening new shipping routes while threatening traditional ways of life. Countries like Canada, Russia, and Norway compete for Arctic resources while indigenous peoples adapt to environmental changes. The melting ice reveals both opportunities and existential threats to global climate stability."
    }
};

export class WorldManager {
    private worlds: World[];

    constructor() {
        this.worlds = [];
    }

    async loadWorld(timePeriods: TimePeriod[]): Promise<void> {
        // Convert time periods to worlds with detailed regions
        this.worlds = timePeriods.map(period => ({
            id: period.id,
            name: period.name,
            description: period.description,
            regions: period.regions.map((regionName, index) => ({
                id: `${period.id}-region-${index}`,
                name: regionName,
                description: REGION_DETAILS[period.id]?.[regionName] || 
                    `Explore the fascinating ${regionName} region during the ${period.name}. This area played a crucial role in shaping the cultural, political, and social landscape of its time, contributing unique innovations and perspectives to human civilization.`,
                timePeriodId: period.id
            }))
        }));
    }

    getWorlds(): World[] {
        return this.worlds;
    }

    getWorldById(worldId: string): World | undefined {
        return this.worlds.find(w => w.id === worldId);
    }

    renderWorld(worldId: string): void {
        const world = this.worlds.find(w => w.id === worldId);
        if (world) {
            console.log(`Rendering world: ${world.name}`);
        } else {
            console.error(`World with id ${worldId} not found.`);
        }
    }
}